name: ml-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.0.2
  - pandas=2.2.2
  - scipy=1.13.1
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.5.0
  - xgboost=2.1.0
  - imbalanced-learn=0.12.3
  - statsmodels=0.14.2
  - pillow
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - japanize-matplotlib==1.1.3
      - ydata-profiling==4.7.0
      - category_encoders==2.6.3
      - streamlit==1.37.1
      - optuna==3.6.1
